In [ ]:
# Este sera o arquivo principal. Aqui nós concentraremos as modificações.
# tfidf vector (conversao de texto em numeros) -> vira uma matriz de frequência:

# 1. Importação dos dados

In [46]:
from sklearn import datasets, neighbors

diabetes = datasets.load_diabetes()
diabetes.data[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187235,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03199144, -0.04664087]])

In [47]:
diabetes.target[:5]

array([ 151.,   75.,  141.,  206.,  135.])

In [48]:
regressor = neighbors.KNeighborsRegressor()

In [49]:
regressor.fit(diabetes.data[:300], diabetes.target[:300])

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [50]:
diabetes_pred = regressor.predict(diabetes.data[300:])
diabetes_pred[:5]

array([ 190.4,  141.6,  162. ,  229.4,  130.8])

In [51]:
diabetes.target[300:][:5]

array([ 275.,   65.,  198.,  236.,  253.])

# 2. Avaliação

In [52]:
from sklearn import metrics

## 2.1 Regressão

In [53]:
metrics.mean_absolute_error(diabetes.target[300:], diabetes_pred)

46.907042253521119

In [54]:
metrics.mean_squared_error(diabetes.target[300:], diabetes_pred)

3437.610704225352

## 2.2 Classificação

In [55]:
classifier = neighbors.KNeighborsClassifier()
iris = datasets.load_iris()
classifier.fit(iris.data, iris.target)
iris_pred = classifier.predict(iris.data)

In [56]:
metrics.accuracy_score(iris.target, iris_pred)

0.96666666666666667

In [57]:
metrics.recall_score(iris.target, iris_pred)

C:\Program Files\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1304: DeprecationWarning: The default `weighted` averaging is deprecated, and from version 0.18, use of precision, recall or F-score with multiclass or multilabel data or pos_label=None will result in an exception. Please set an explicit value for `average`, one of (None, 'micro', 'macro', 'weighted', 'samples'). In cross validation use, for instance, scoring="f1_weighted" instead of scoring="f1".
  sample_weight=sample_weight)


0.96666666666666667

### 2.2.1 Validação Cruzada

In [58]:

from sklearn.model_selection import cross_val_score

ImportError: No module named 'sklearn.model_selection'

In [26]:
cross_val_score(classifier, iris.data, iris.target, cv=10, verbose=3, scoring='accurary')

ValueError: 'accurary' is not a valid scoring value. Valid options are ['accuracy', 'adjusted_rand_score', 'average_precision', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'log_loss', 'mean_absolute_error', 'mean_squared_error', 'median_absolute_error', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc']

In [24]:
import numpy as np
scores = cross_val_score(classifier, iris.data, iris.target, cv=10, verbose=3, scoring='accurary')
np.mean(scores)

NameError: name 'cross_val_score' is not defined